name: Personal Finance Evolved
favicon: null
layout_spectrum: 0
typography_spectrum: 0.04488251591101289
title: Personal Finance Evolved
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff6600'
    - '#ffc8a3'
    - '#ff9a58'
    - '#ffdcc4'
  brandStrength: 0.2923271234612912
  lightness: 0.44105854583904147
  saturation: 0.48496645223349333
  rhythmicContrast: 0.7026644668076187
purpose: []
